fix: update GitHub Actions workflow to include dev

diff --git a/.github/workflows/github-action.yml b/.github/workflows/github-action.yml
--- a/.github/workflows/github-action.yml
+++ b/.github/workflows/github-action.yml
@@ -2,9 +2,9 @@ name: IRC CI
 run-name: Compilation
 on:
   push:
-    branches: [ main ]
+    branches: [ main, dev]
   pull_request:
-    branches: [ main ]
+    branches: [ main, dev]
 
 jobs:
   Compilation:
@@ -29,34 +29,32 @@ jobs:
           echo "🚀 Starting IRC..."
           timeout 2s ./ircserv 6667 password || [ $? -eq 124 ]
           echo "✅ IRC started successfully!"
-     
-      # Uncomment when parsing/server is merged
 
-      # - name: Test wrong argument count
-      #   run: |
-      #     echo "🔎 Testing wrong argument count..."
-      #     ./ircserv; [ $? -eq 2 ]
-      #     ./ircserv 6667; [ $? -eq 2 ]
-      #     echo "✅ Wrong argument count handled correctly!"
+      - name: Test wrong argument count
+        run: |
+          echo "🔎 Testing wrong argument count..."
+          ./ircserv; [ $? -eq 2 ]
+          ./ircserv 6667; [ $? -eq 2 ]
+          echo "✅ Wrong argument count handled correctly!"
       
-      # - name: Test wrong argument count
-      #   run: |
-      #     echo "🔎 Testing wrong argument count..."
-      #     ./ircserv; [ $? -eq 2 ]
-      #     ./ircserv 6667; [ $? -eq 2 ]
-      #     ./ircserv 6667 password idk; [ $? -eq 2 ]
-      #     echo "✅ Wrong argument count handled correctly!"
+      - name: Test wrong argument count
+        run: |
+          echo "🔎 Testing wrong argument count..."
+          ./ircserv; [ $? -eq 2 ]
+          ./ircserv 6667; [ $? -eq 2 ]
+          ./ircserv 6667 password idk; [ $? -eq 2 ]
+          echo "✅ Wrong argument count handled correctly!"
 
-      # - name: Test invalid port
-      #   run: |
-      #     echo "🔎 Testing invalid port..."
-      #     ./ircserv 0 password; [ $? -eq 1 ]
-      #     ./ircserv 99999 password; [ $? -eq 1 ]
-      #     echo "✅ Invalid port handled correctly!"
+      - name: Test invalid port
+        run: |
+          echo "🔎 Testing invalid port..."
+          ./ircserv 0 password; [ $? -eq 1 ]
+          ./ircserv 99999 password; [ $? -eq 1 ]
+          echo "✅ Invalid port handled correctly!"
 
-       # - name: Test empty password
-      #   run: |
-      #     echo "🔎 Testing empty password..."
-      #     ./ircserv 6667 ""; [ $? -eq 1 ]
-      #     echo "✅ Empty password handled correctly!"
+      - name: Test empty password
+        run: |
+          echo "🔎 Testing empty password..."
+          ./ircserv 6667 ""; [ $? -eq 1 ]
+          echo "✅ Empty password handled correctly!"
 
